apiVersion: config.ocm.software/v1alpha1
kind: ConfigData
metadata:
  name: ocm-config
localization:
  - name: image
    file: deployment.yaml
    image: spec.template.spec.containers[0].image
    resource:
      name: image
  - name: replicaSet
    file: deployment.yaml
    image: spec.replicas
    resource:
      name: replicaSet
      value: 2